site_name: Ransomware Aanvallen en juridische dillema's
markdown_extensions: 
  - footnotes

site_url: ""
use_directory_urls: false 
plugins: []
site_author: Britt Bijlstra 
theme: 
  name: material
  language: nl
  features: 
    - navigation.instant
    - navigation.top 
    - toc.integrate
    - content.code.annotate
    - content.tabs.link 


markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.betterem
  - pymdownx.tilde

nav:
  - Home: index.md

